#!/bin/bash
%scp tsp_c++_angela.cpp ydong@genuse62.smu.edu:~/mvbpmp-cpp-gurobi/
%scp BPMP.cpp ydong@genuse62.smu.edu:~/mvbpmp-cpp-gurobi/
%scp readData.h ydong@genuse62.smu.edu:~/mvbpmp-cpp-gurobi/
%scp BPMP_benders_using_callback.cpp ydong@genuse62.smu.edu:~/mvbpmp-cpp-gurobi/
%scp BPMP_benders_nocallback.cpp ydong@genuse62.smu.edu:~/mvbpmp-cpp-gurobi/
%scp MVBPMP_LR.cpp ydong@genuse62.smu.edu:~/mvbpmp-cpp-gurobi/
%scp MVBPMP.cpp ydong@genuse62.smu.edu:~/mvbpmp-cpp-gurobi/
%scp openmptest.cpp ydong@genuse62.smu.edu:~/mvbpmp-cpp-gurobi/
%scp openmp_example_pi.cpp ydong@genuse62.smu.edu:~/mvbpmp-cpp-gurobi/
%scp openmp_example_pi_padding.cpp ydong@genuse62.smu.edu:~/mvbpmp-cpp-gurobi/
%scp openmp_example_pi_critical.cpp ydong@genuse62.smu.edu:~/mvbpmp-cpp-gurobi/
%scp openmp_example_for_num_threads.cpp ydong@genuse62.smu.edu:~/mvbpmp-cpp-gurobi/
%scp openmp_example_pi_reduction.cpp ydong@genuse62.smu.edu:~/mvbpmp-cpp-gurobi/
%scp openmp_test_mvbpmp.cpp ydong@genuse62.smu.edu:~/mvbpmp-cpp-gurobi/
%scp openmp_test_mvbpmp_john.cpp ydong@genuse62.smu.edu:~/mvbpmp-cpp-gurobi/
%scp MVBPMP_LR_openmp.cpp ydong@genuse62.smu.edu:~/mvbpmp-cpp-gurobi/
%scp BPMP_LR.cpp ydong@genuse62.smu.edu:~/mvbpmp-cpp-gurobi/
scp BPMP_DW-CG.cpp ydong@genuse62.smu.edu:~/mvbpmp-cpp-gurobi/
